spring:
  config:
    import: file:.env[.properties]
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DRIVER}
    url: ${URL}
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
  security:
    jwt:
      secret: ${JWT_SECRET}
      access: 86400000

  liquibase:
    changeLog: classpath:liquibase/changelog.yml
    defaultSchema: ${DEFAULT_SCHEMA}
    enabled: true
