server:
  port: 8080

enable:
  link: http://localhost:${server.port}/api/auth/enable/

spring:
  datasource:
    username:
    password:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/

  sql:
    init:
      mode: never
      continue-on-error: false
      data-locations: classpath:db/tests/demo_data.sql

  security:
    jwt:
      secret:
      #      24 hours * 1
      access: 86400000
      #      24 hours * 30
      refresh: 2592000000

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true