spring:
  config:
    import: file:.env[.properties]

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER}
    url: ${DB_URL}

  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:db_tests/demo_data.sql

  security:
    jwt:
      secret: ${JWT_SECRET}
#      24 hours * 1
      access: 86400000
#      24 hours * 30
      refresh: 2592000000

  liquibase:
    changeLog: classpath:liquibase/changelog.yml
    defaultSchema: ${DB_DEFAULT_SCHEMA}
    enabled: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true