enable:
  link: 194.146.39.99:8080/api/auth/enable/

spring:

  datasource:
    username: postgres
    password: nikita
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://task-tracker-postgres:5432/my-task-tracker-db

  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:db_tests/demo_data.sql

  security:
    jwt:
      secret: gSlrTZoP7iFZP6c1m9f6h1JwNP2X89+y0JHQ3EXo/hklG2euXqSMEbfpMqY0KaqH
      #      24 hours * 1
      access: 86400000
      #      24 hours * 30
      refresh: 2592000000

  liquibase:
    changeLog: classpath:liquibase/changelog.yml
    defaultSchema: public
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: task.tracker.info1@gmail.com
    password: xtyq tsbl ucyp rcsn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true