enable:
  link: localhost:8080/api/auth/enable/

spring:

  datasource:
    username:
    password:
    driverClassName: org.postgresql.Driver
    url:

  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:db/tests/demo_data.sql

  security:
    jwt:
      secret:
      #      24 hours * 1
      access: 86400000
      #      24 hours * 30
      refresh: 2592000000

  liquibase:
    changeLog: classpath:liquibase/changelog.yml
    defaultSchema:
    enabled: false

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true