server:
  port: 8080

enable:
  link: localhost:${server.port}/api/auth/enable/

spring:
  datasource:
    username: nikita
    password: nikita
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

  sql:
    init:
      mode: never
      continue-on-error: false
      data-locations: classpath:db/tests/demo_data.sql

  security:
    jwt:
      secret: gSlrTZoP7iFZP6c1m9f6h1JwNP2X89+y0JHQ3EXo/hklG2euXqSMEbfpMqY0KaqH
      #      24 hours * 1
      access: 86400000
      #      24 hours * 30
      refresh: 2592000000

  mail:
    host: smtp.gmail.com
    port: 587
    username: task.tracker.info1@gmail.com
    password: xtyq tsbl ucyp rcsn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true