create table if not exists "project"
(
    id         bigint generated by default as identity
        constraint project_pk
            primary key,
    name       varchar   not null
        constraint check_name
            check ((length((name)::text) >= 3) AND (length((name)::text) <= 20)),
    created_at timestamp not null
);


create unique index if not exists project_name_uindex
    on project (name);


create table if not exists "task-state"
(
    id                     bigint generated by default as identity
        constraint "task-state_pk"
            primary key,
    name                   varchar   not null
        constraint check_name
            check ((length((name)::text) >= 3) AND (length((name)::text) <= 20)),
    created_at             timestamp not null,
    project_id             bigint
        constraint "task-state_project_id_fk"
            references project
            on delete cascade,
    next_task_state_id     bigint
        constraint fkspmwqo3pk0jbuadp4bjfffdga
            references "task-state"
            on delete cascade,
    previous_task_state_id bigint
        constraint fke5a6oj4458pqqiywvjbk6bfu
            references "task-state"
            on delete cascade
);


create table if not exists "task"
(
    id            bigint generated by default as identity
        constraint task_pk
            primary key,
    name          varchar   not null
        constraint check_name
            check ((length((name)::text) >= 3) AND (length((name)::text) <= 20)),
    created_at    timestamp not null,
    description   varchar(100),
    task_state_id bigint    not null
        constraint fk5uliw0cjhf7w27o9wx5pygugy
            references "task-state"
            on delete cascade
);
