drop table if exists "databasechangelog";
drop table if exists "databasechangeloglock";


drop table if exists "task";
drop table if exists "task-state";
drop table if exists "project";
drop table if exists "user";

create table if not exists "user"
(
    id       bigint generated by default as identity
        constraint user_pk
            primary key,
    username varchar not null,
    password varchar not null,
    email    varchar not null,
    role     varchar not null
);

create unique index user_email_uindex
    on "user" (email);

create unique index user_username_uindex
    on "user" (username);

create table if not exists "project"
(
    id         bigint generated by default as identity
        constraint project_pk
            primary key,
    name       varchar   not null
        constraint check_name
            check ((length((name)::text) >= 3) AND (length((name)::text) <= 20)),
    created_at timestamp not null,
    user_id    bigint    not null
        constraint project_user_id_fk
            references "user"
            on delete cascade
);

create table if not exists "task-state"
(
    id                     bigint generated by default as identity
        constraint "task-state_pk"
            primary key,
    name                   varchar   not null
        constraint check_name
            check ((length((name)::text) >= 3) AND (length((name)::text) <= 20)),
    created_at             timestamp not null,
    project_id             bigint
        constraint "task-state_project_id_fk"
            references project
            on delete cascade,
    next_task_state_id     bigint
        constraint fkspmwqo3pk0jbuadp4bjfffdga
            references "task-state"
            on delete cascade,
    previous_task_state_id bigint
        constraint fke5a6oj4458pqqiywvjbk6bfu
            references "task-state"
            on delete cascade
);

create table if not exists "task"
(
    id            bigint generated by default as identity
        constraint task_pk
            primary key,
    name          varchar   not null
        constraint check_name
            check ((length((name)::text) >= 3) AND (length((name)::text) <= 20)),
    created_at    timestamp not null,
    description   varchar(100),
    task_state_id bigint    not null
        constraint fk5uliw0cjhf7w27o9wx5pygugy
            references "task-state"
            on delete cascade
);


-- "user"
INSERT INTO "user" (username, password, email, role)
-- password
VALUES
    ('user1', '$2a$10$h8tF9AQttfqv/FjMihPtou.dV.Fimrs0e1rCT/zBFU7I/hT4qyCvO', 'user1@example.com', 'USER'),
    ('user2', '$2a$10$h8tF9AQttfqv/FjMihPtou.dV.Fimrs0e1rCT/zBFU7I/hT4qyCvO', 'user2@example.com', 'USER');

--  "project"
INSERT INTO "project" (name, created_at, user_id)
VALUES
    ('Project 1', current_timestamp, 1),
    ('Project 2', current_timestamp, 2);

--  "task-state"
INSERT INTO "task-state" (name, created_at, project_id, next_task_state_id, previous_task_state_id)
VALUES
    ('State 1', current_timestamp, 1, 2, NULL),
    ('State 2', current_timestamp, 1, NULL, 1),
    ('State 3', current_timestamp, 2, NULL, NULL);

--  "task"
INSERT INTO "task" (name, created_at, description, task_state_id)
VALUES
    ('Task 1', current_timestamp, 'Description 1', 1),
    ('Task 2', current_timestamp, 'Description 2', 2);